### ISSUE TITLE
Does not work in XCODE 11

### ISSUE THREAD

**Issue by tskapo** [AlwaysRightInstitute/VueXcode#1]
Does not work in XCODE 11

**Unsupported Swift Version**

The target “VueXcode” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.

**Comment by helje5** [comment]
Ah, you can't build it in Xcode. Fair enough!

**Comment by helje5** [comment]
Fixed in 1.0.5
